

# This file was *autogenerated* from the file case64_sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_24 = Integer(24); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_25 = Integer(25); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5)# Erdos #388 case (6,4): independent integral-point computation in SageMath.
# Curve C: u^2 = t^3 + 10 t^2 + 24 t + 1  (model [0,10,0,24,1])
# Run: mamba run -n e388sage sage case64_sage.sage
E = EllipticCurve([_sage_const_0 , _sage_const_10 , _sage_const_0 , _sage_const_24 , _sage_const_1 ])
print("curve:", E.ainvs())
print("minimal model:", E.minimal_model().ainvs())
print("conductor:", E.conductor().factor())
print("torsion:", E.torsion_order())
print("rank (proven bounds):", E.rank(only_use_mwrank=False), "certified:", E.rank_bounds())
gens = E.gens(proof=True)
print("MW generators (proof=True):", gens)
pts = E.integral_points(both_signs=True)
print("integral points (both signs):", sorted((P[_sage_const_0 ], P[_sage_const_1 ]) for P in pts))
# filter to Erdos-388 (6,4) solutions: t = x^2+7x+6, u = y^2+5y+5, x,y >= 1
sols = []
for P in pts:
    t, u = P[_sage_const_0 ], P[_sage_const_1 ]
    d1 = _sage_const_4 *t + _sage_const_25 
    if d1 >= _sage_const_0  and Integer(d1).is_square():
        a = sqrt(Integer(d1))
        for xx in [(a - _sage_const_7 )/_sage_const_2 , (-a - _sage_const_7 )/_sage_const_2 ]:
            if xx in ZZ and xx >= _sage_const_1 :
                d2 = _sage_const_4 *u + _sage_const_5 
                if d2 >= _sage_const_0  and Integer(d2).is_square():
                    b = sqrt(Integer(d2))
                    for yy in [(b - _sage_const_5 )/_sage_const_2 , (-b - _sage_const_5 )/_sage_const_2 ]:
                        if yy in ZZ and yy >= _sage_const_1 :
                            sols.append((xx, yy))
print("positive-integer solutions (x,y) of (x+1)..(x+6)=(y+1)..(y+4):", sorted(set(sols)))

